### ISSUE TITLE
LinkedIn website changed and scrapedin can't read basic data. 

### ISSUE THREAD

**Issue by deepsidh9** [linkedtales/scrapedin#67] opened 2020-02-12 08:33 UTC
Encountered this issue.
(node:49799) UnhandledPromiseRejectionWarning: Error: LinkedIn website changed and scrapedin can't read basic data. 
As it said : "Please report this issue at https://github.com/linkedtales/scrapedin/issues" , i am reporting this.

**Comment by ZeeIOS** [comment] 2020-02-18 10:35
sed

**Comment by leonardiwagner** [comment] 2020-02-18 11:05
@deepsidh9 , @rovisal , @srbartlett and @christinajones-dev can you guys tell me if it's still happening?

I've been doing some tests and it's working, otherwise please download the page you want to scrap (Save As in the browser) and send me via leonardiwagner@gmail.com because it can be a regional issue or an update that's only showing to you guys, thank you.

**Comment by christinajones-dev** [comment] 2020-02-18 11:11
Hi @leonardiwagner, thank you for your response.
I had this issue just a day ago. I sent you complete logs and some screenshots on the email address you mentioned.

**Comment by christinajones-dev** [comment] 2020-02-18 11:28
> @deepsidh9 , @rovisal , @srbartlett and @christinajones-dev can you guys tell me if it's still happening?
> 
> I've been doing some tests and it's working, otherwise please download the page you want to scrap (Save As in the browser) and send me via [leonardiwagner@gmail.com](mailto:leonardiwagner@gmail.com) because it can be a regional issue or an update that's only showing to you guys, thank you.

My bad, I was not testing it properly. Now I understood its working and working fine. Thanks.

> @deepsidh9 , @rovisal , @srbartlett and @christinajones-dev can you guys tell me if it's still happening?
> 
> I've been doing some tests and it's working, otherwise please download the page you want to scrap (Save As in the browser) and send me via [leonardiwagner@gmail.com](mailto:leonardiwagner@gmail.com) because it can be a regional issue or an update that's only showing to you guys, thank you.

I'm not having it anymore, I was doing something wrong from my end. Now its working fine.

**Comment by christinajones-dev** [comment] 2020-02-18 11:29
I'm not having it anymore, I was doing something wrong from my end. Now its working fine.

**Comment by srbartlett** [comment] 2020-02-19 10:11
Working for me.  However, the problem appears to be related to the cookies file.  

It stopped working when I exported a new cookies file (using the Chrome plugin). Reverting to an older cookies file fixed the problem.  I am using version 1.0.11.  Running non-headless confirms the profile is loaded using a non authenticated user.

**Comment by leonardiwagner** [comment] 2020-02-20 12:05
@srbartlett I'm going to investigate that, thank you for reporting! Just update your version to 1.0.12 because it fixed a LinkedIn change: #68

**Comment by AdityaAnand1** [comment] 2020-04-09 03:58
This is still happening, although it happens randomly, even for the same exact profile which is rather weird.

Any ideas @leonardiwagner, perhaps try running via crawler and it should be reproducible. I'm encountering this approximately once every ~10 or so profiles

**Comment by leonardiwagner** [comment] 2020-04-09 15:21
@ChoqueCastroLD , @AdityaAnand1 are you guys using login by password or via cookies? 

> perhaps try running via crawler and it should be reproducible. I'm encountering this approximately once every ~10 or so profiles

that intermittent error sounds like the session is lost for that given try to crawl, maybe something related with cookies, I'll provide more debuggable information when it occurs and investigate how that session is being lost sometimes

I really appreciate help for finding any issue in the code, meanwhile, you guys can confirm if using another login approach solve that issue.

**Comment by AdityaAnand1** [comment] 2020-04-10 08:31
This happened for me when using cookies.

When using a new account, the account was blocked after ~50 or so profiles scraped in an hour.

When using a paid account and scraping ~400 profiles in ~3 hrs, the account was auto-logged out (cookie was invalidated) and when I signed back in, I got a recaptcha.

Also, @leonardiwagner do you have any tips for optimal rate of scraping, I'm just trying to figure it out by trial and error right now. Seems to be working steadily at ~60 requests per hour with one paid account. (though this is excruciatingly slow as I need to figure out a way to scrape >250k profiles)

**Comment by neverton1970** [comment] 2020-04-10 14:34
Hi guys, I've just come here because I was getting the same error message "LinkedIn website changed and can't read basic data", just refreshed the cookies I was using and it's working now so it might be expired cookies

**Comment by raphaelpreston** [comment] 2020-05-10 20:05
I'll join in the party. I'm scraping 500+ profiles and I'd say that it's happening fairly randomly. When it happens, it seems like a coin flip whether or not it will happen again immediately (since it's retrying on the same profile) or it will just continue on like normal. If it continues to happen on that profile, then running it in non-headless will fix it every time.

**Comment by kf6kjg** [comment] 2020-05-12 17:22
As there's been a several fixes to the codebase since this was reported, and the most recent comments seem to indicate that the basic issues have been resolved, I'm closing this.  If there's a resurgence of such errors, please open a new issue report.

Thank you to everyone who helped with the diagnostics for this!

**Closed by kf6kjg** 2020-05-12 17:22 UTC
Labels: waiting for response
